### ISSUE TITLE
Doesn't explain how to install

### ISSUE THREAD

**Issue by fernandobarahona** [FrogSquare/GDFirebase#2]
I haven't been able to find how to install the plugins. I don't find the plugin file [plugin].aar nor the the config file plugin.gdap

Sorry, i'am not an adroid expert. So maybe with the modification of the build.gradle something should happened so i can use something from gdscript to use google libraries, but still i would't know how. 

Sorry if i just dont find the documentation, but i have look all over the repository and havent find it. 

Thanks for the reply and sorry for comunicating here but i dont know other way.

**Comment by RameshRavone** [comment]
Pre-build files are in the release section,

https://github.com/FrogSquare/GDFirebase/releases/download/0.1/gdfirebase-0.1.zip

**Comment by RameshRavone** [comment]
Alternatively you can use the script as well

This is an installer script prepared so it will update the Android Manifest file and build.gradle files as well

https://gist.github.com/RameshRavone/5b00e9d098e1f7bf034aed4cafac8c80#file-gdfirebase

**Comment by fernandobarahona** [comment]
Thank you very much for the very fast response. I'll try it now.
